<?php
/* PV 2023-02-14: This file overrides application/view/common/linked-resources.phthml
 * The labels in the default linked resources reflect the label and class of the parent
 * For journals, I prefer the publication date...
 */


$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$fragment = 'item-linked';
if ('Omeka\Api\Representation\ItemSetRepresentation' === get_class($objectResource)) {
    $fragment = 'item-set-linked';
}
$pagination = $this->pagination(null, $totalCount, $page, $perPage);
$pagination->setFragment($fragment);

if ($this->status()->isSiteRequest()) {
    $filterLocale = (bool) $this->siteSetting('filter_locale_values');
    $lang = $this->lang();
} else {
    $filterLocale = false;
    $lang = null;
}
$tagTerms =['schema:dateIssued'];

?>
<div id="linked-resources">
<div class="linked-header">

    <div id="linked-filter">
        <h4><?php echo $translate('Filter by property'); ?></h4>
        <select id="filter-property" name="property" data-url="<?php echo $escape($this->url(null, [], true)); ?>" data-fragment="<?php echo $escape($fragment); ?>">
            <option value=""><?php echo $translate('All'); ?></option>
            <?php foreach ($properties as $prop): ?>
            <option value="<?php echo $escape($prop->id()); ?>"<?php echo $prop->id() == $property ? ' selected="selected"' : ''; ?>><?php echo $escape(sprintf('%s (%s)', $translate($prop->label()), $prop->term())); ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php echo ($totalCount > $perPage) ? $pagination : ''; ?>
</div>

<?php foreach ($subjectValues as $term => $values):
 ?>
<table>
<caption class="linked-resource-property"><?php echo $escape($this->translate($values[0]->property()->label())); ?></caption>
<thead>
    <tr>
    <th><?php echo $translate('Title'); ?></th>
    <th><?php echo $translate('Alternate label'); ?></th>
    <!--<th><?php //echo $translate('Class'); ?></th>-->
    </tr>
</thead>
<tbody>
    <?php foreach ($values as $value): ?>
    <?php
	 
    $template = $value->resource()->resourceTemplate();
    $templateProperty = $template ? $template->resourceTemplateProperty($value->property()->id()) : null;
    $altLabel = $templateProperty ? $templateProperty->alternateLabel() : null;
    ?>
    <tr class="linked-resource">
	<?php
	//PV 2023-02-16 Added custom code to see if an object is a publicationIssue
	//if so, the alternate label is exchanged with the publication date.
	if($value->resource()->resourceClass()):
	 $rcl=strtolower($value->resource()->resourceClass()->label()); //fetch the resource-label
	 endif;
	 if(isset($rcl)){
	 if(str_contains($rcl,'publicationissue')):
		$tagTerm=$tagTerms[0];
		$fields=$value->resource()->values();
		$pd=$fields[$tagTerm]['values'][0];
		$altLabel=$pd;
	endif;
	 }
	
	?>
	
        <td><?php echo $value->resource()->linkPretty('square', null, null, null, ($filterLocale ? $lang : null)); ?></td>
        <td>
        <?php if ($altLabel): ?>
        <span class="alternate-label"><?php echo $this->escapeHtml($altLabel) ?></span>
        <?php endif; ?>
        </td>
		<!-- PV 20230228 at explicit request from  Ineke is this column removed...
        <td>
		-->
        <?php //if ($value->resource()->resourceClass()): ?>
        <!-- <span class="resource-class"><?php //echo $this->escapeHtml($translate($value->resource()->resourceClass()->label())); ?></span>-->
        <?php //endif; ?>
        <!--</td>-->
    </tr>
    <?php endforeach; ?>
</tbody>
</table>
<?php endforeach; ?>

<?php echo ($totalCount > $perPage) ? '<div class="linked-footer">' . $pagination . '</div>' : ''; ?>

</div>

<script>
$('#filter-property').on('change', function(e) {
    var thisSelect = $(this);
    var property = thisSelect.find(':selected').val();
    var url = thisSelect.data('url');
    var fragment = thisSelect.data('fragment');
    window.location = url + '?' + $.param({property: property}) + '#' + fragment;
});
</script>
