<?php
// Customized version of 'application/view/omeka/site/item-set/browse.phtml' from Omeka S core version 4.1.1
// Customizations:
// - custom feature Renamed to Collections
// - custom feature Show amount of total collections
// - custom feature Disable advanced search in browse controls
// - custom feature Show amount for searchFilter
// - custom feature Thumbnail, heading and decription layout

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$this->htmlElement('body')->appendAttribute('class', 'item-set resource browse');
?>

<?php
    // BEGIN custom feature Renamed to Collections
    echo $this->pageTitle($this->translate('Collections'), 2);
    // END custom feature Renamed to Collections
?>

<?php
    // BEGIN custom feature Show amount of total collections
    $filters = $this->searchFilters();
    // END custom feature Show amount of total collections
?>

<div id="total-results" class="browse-controls">
    <?php
        // BEGIN custom feature Show amount of total collections
        echo $this->pagination() . "collection(s)";
        //END custom feature Show amount of total collections
    ?>

    <?php
        // BEGIN custom feature Disable advanced search in browse controls
        //echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'advanced-search']);
        // END custom feature Disable advanced search in browse controls
    ?>
    <?php
        // BEGIN custom feature Show amount for searchFilter
        if($filters){ echo " for " . $filters; }
        // END custom feature Show amount for searchFilter
    ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
    <?php
    $headingTerm = $this->siteSetting('browse_heading_property_term');
    $bodyTerm = $this->siteSetting('browse_body_property_term');
    foreach ($itemSets as $itemSet):
        $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $itemSet->displayTitle(null, $valueLang);
        $body = $bodyTerm ? $itemSet->value($bodyTerm, ['lang' => $valueLang]) : $itemSet->displayDescription(null, $valueLang);
    ?>
        <li class="item-set resource">
            <!-- BEGIN custom feature Thumbnail, heading and decription layout -->
            <div class="item-set-thumb">
                <?php echo $itemSet->linkRaw($thumbnail($itemSet, 'medium')); ?>
            </div>
            <div class="item-set-metadata">
                <h4><?php echo $itemSet->link($heading); ?></h4>
                <?php if ($body): ?>
                    <div class="description"><?php echo $escape($body); ?></div>
                <?php endif; ?>
            </div>
            <!-- END custom feature Thumbnail, heading and decription layout -->
        </li>
    <?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
