<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

// Array of MIME-types supported by ModelViewer.
// For a complete list, see https://github.com/Daniel-KM/Omeka-S-module-ModelViewer#media-types-and-security-issue
$mediaTypes3D = [
		"application/octet-stream",
		"application/vnd.threejs+json",
		"model/gltf-binary",
		"model/gltf+json",
		"model/obj",
		"model/vnd.collada+xml",
		"model/vnd.filmbox",
		"image/ktx2",
		"model/mtl"
		];
?>

<div id="item-page">
	<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
	<h3><?php echo $translate('Item'); ?></h3>
	<?php $this->trigger('view.show.before'); ?>
	
	
	<div id="item-page-media">
	<?php
	// Code to determine the class of the resource
	if ($item->resourceClass()):
		// Get the resource class label and replace spaces in order to use it in relevant element classes so that display can react.
		$rc=str_replace(" ", "-", strtolower($item->resourceClass()->label()));
	else:
		$rc="none";
	endif;

	$imc=count($itemMedia); //imc =item media count;
	$mbc="";
	if ($imc>1):
		// if more than one media item, add 'split' to several element classes
		// Note: Currently, only CSS class 'media-embeds.message.split' will be rendered side-by-side
		$mbc = "split";
		//$mbc=mediabox-class
	endif;

	# Check if this itemMedia contains 3D model
	if ($rc == "3dmodel"):
		$model3d = True ;
	else:
		$model3d = False ;
	endif;
	?>

	<?php if ($embedMedia && $itemMedia): ?>

		<?php if ($model3d): ?>
			<!-- When 3D model data, render only the 3D itemMedia and skip all other media -->
			<div class="media-embeds">
			<?php foreach ($itemMedia as $media): ?>
				<?php if (in_array($media->mediaType(), $mediaTypes3D)) : ?>
					<div class="media-box <?php echo $rc;?>">
					<div class="media-box-header">
						Media Titel:&nbsp; <?php if ($media->displayTitle()): echo $media->displayTitle(); endif; ?>
					</div>
					<div class="media-box-content">
					<?php echo $media->render();?>
					</div>
					</div>
				<?php endif; ?>
			<?php endforeach; ?>
			</div>

		<?php else: ?>
			<!-- Render all itemMedia in all other cases -->
			<div class="media-embeds <?php echo $rc ." ".$mbc ;?>">
			<?php foreach ($itemMedia as $media):?>
				<div class="media-box <?php echo $rc;?>">
				<div class="media-box-header">
					Media Titel:&nbsp; <?php if ($media->displayTitle()):echo $media->displayTitle(); endif; ?>
				</div>
				<div class="media-box-content">
				<?php echo $media->render();?>
				</div>
				</div>
			<?php endforeach;?>
			</div>
		<?php endif; ?>
	<?php endif; ?>

	</div> <!-- close div "item-page-media" -->
	<div id="item-page-properties">
	<div class="properties">
	
	
	
	
	<div class="resource-class property">
	<?php if ( $item->resourceClass()): ?>
	<!--<h4>Resource class</h4>
		<div class="values"><div class="value"><?php echo $escape($translate($item->resourceClass()->label())); ?></div></div>-->
	 <?php endif; ?>
	</div>

	<?php echo $item->displayValues(); ?>

	<div class="property">
	<!--span style="background-color:red; color:white">values</span-->
		<?php $itemSets = $item->itemSets(); ?>
		<?php if (count($itemSets) > 0): ?>
		<h4><?php echo $translate('Item sets'); ?></h4>
		<div class="values">
			<?php foreach ($itemSets as $itemSet): ?>
			<div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
			<?php endforeach; ?>
		</div>
		<?php endif; ?>
	</div>
	<?php if (!$embedMedia && $itemMedia): ?>
	<div class="media-list property">
		<h4><?php echo $translate('Media'); ?></h4>
		<div class="values">
		<?php foreach ($itemMedia as $media): ?>
		
		
			<?php echo $media->linkPretty(); ?>
		<?php endforeach; ?>
		</div>
	</div>
	<?php endif; ?>
	
	</div>
	
	</div>


    <div id="resources-linked" class="section">
        <?php
        $subjectValues = $item->displaySubjectValues([
            'page' => $this->params()->fromQuery('page', 1),
            'perPage' => 25,
            'resourceProperty' => $this->params()->fromQuery('resource_property'),
        ]);
        ?>

        <?php if ($subjectValues): ?>
        <div id="item-linked">
            <h3><?php echo $translate('Linked resources'); ?></h3>
            <?php echo $subjectValues; ?>
        </div>
        <?php endif; ?>
    </div>
</div>
<?php $this->trigger('view.show.after'); ?>
<div id="manifest-link">
			Get some text in....
			<?= $this->iiifManifestLink($item) ?>
		</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(document).trigger('enhance.tablesaw');        
    });
</script>
