<?php
// Customized version of 'application/view/omeka/site/item/show.phtml' from Omeka S core version 4.1.1
// Customizations:
// - custom feature Show item sets: Show the item sets to which the item belongs in the metadata section
// - custom feature Disable resourcePageBlocks: Do not render resource page blocks by default, but leave this to the theme code in this file
// - custom feature Differentiate on mediaType: Render Audio and Video (AV), 3D and PDF media directly; use the IIIF viewer configured in the theme for all other cases

$translate = $this->plugin('translate');
// BEGIN custom feature Show item sets
$escape = $this->plugin('escapeHtml');
//END custom feature Show item sets

// BEGIN custom feature Disable resourcePageBlocks
//$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
// END custom feature Disable resourcePageBlocks

$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;


// BEGIN custom feature Differentiate on mediaType

// Code to determine the class of the resource
if ($item->resourceClass()):
    // Get the resource class label and replace spaces in order to use it in relevant element classes so that display can react.
    $rc=str_replace(" ", "-", strtolower($item->resourceClass()->label()));
else:
    $rc="none";
endif;

$imc=count($item->media()); //imc : item media count;
$mbc="";
if ($imc>1):
    // if more than one media item, add 'split' to several element classes
    // Note: Currently, only CSS class 'media-embeds.message.split' will be rendered side-by-side
    $mbc = "split";
    //$mbc=mediabox-class
endif;

?>

<div id="item-page">
    <?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 2); ?>
    <h3><?php echo $translate('Item'); ?></h3>
    <?php $this->trigger('view.show.before'); ?>

    <div id="item-page-media">
        <?php echo $this->partial('um-common/render-item-media', ['item' => $item, 'rc' => $rc, 'mbc' => $mbc]); ?>
    </div>

    <div id="item-page-properties">
        <div class="properties">

            <?php echo $item->displayValues(); ?>

            <!-- BEGIN custom feature Show item sets -->
            <div class="property">
                <?php $itemSets = $item->itemSets(); ?>
                <?php if (count($itemSets) > 0): ?>
                    <h4><?php echo $translate('Item sets'); ?></h4>
                    <div class="values">
                        <?php foreach ($itemSets as $itemSet): ?>
                            <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
            <!-- END custom feature Show item sets -->
        </div>
    </div>

    <div id="resources-linked" class="section">
        <?php
        $subjectValues = $item->displaySubjectValues([
            'page' => $this->params()->fromQuery('page', 1),
            'perPage' => 25,
            'resourceProperty' => $this->params()->fromQuery('resource_property'),
        ]);
        ?>

        <?php if ($subjectValues): ?>
            <div id="item-linked">
                <h3><?php echo $translate('Linked resources'); ?></h3>
                <?php echo $subjectValues; ?>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php
// END custom feature Differentiate on mediaType
?>


<?php
// BEGIN custom feature Disable resourcePageBlocks
//echo $this->resourcePageBlocks($item)->getBlocks();
// END custom feature Disable resourcePageBlocks
?>
<?php $this->trigger('view.show.after'); ?>
