<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var string $resourceType
 * @var string $heading
 * @var string $linkText
 * @var array $components
 * @var array $query
 *
 * Passed from other templates
 * @var string $thumbnailType
 * @var bool $useItemMetadata
 *
 * Removed during migration to Omeka S block Asset and not managed for now:
 * @var array $sortHeadings
 * @var array|false $pagination
 * @todo Manage pagination for gallery (or convert for block search-and-result without form).
 *
 * @copyright 2013, Codrops
 * @copyright 2020-2025, Daniel Berthereau
 * @link https://github.com/Daniel-KM/ThumbnailGridExpandingPreview
 * @license MIT http://tympanus.net/codrops/licensing/
 *
 * The original template was fixed by KevinMwangi and updated newer version of components (modernizr, smartresize, imagesloaded).
 * Then components were removed and only native javascript is used.
 */

use Soap\Url;

// The thumbnail type can be passed via the block query too: ?thumbnail_type=xxx (square, medium, large).


/* = UM-Code Customization ===========================================================
 * Customized template file, derived from Module Block Plus: version 3.4.42
 * 
 * Customizations:
 * - custom feature: Removed CSS from this file
 * - custom feature: Corrected javascript file
 * - custom feature: Modified body display - including link.
 * -
 *
 *
 *
 * ===================================================================================*/


$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// Append in header is not possible with browse preview, so css and js are set in body, even if it is not standard.
$assetUrl = $plugins->get('assetUrl');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $plugins->get('lang')();
$langValue = $filterLocale ? [$lang, ''] : null;

// $showThumbnail = in_array('thumbnail', $components);
$showHeading = in_array('resource-heading', $components);
$showBody = in_array('resource-body', $components);
//--- Start feature: Removed CSS from this file ---
$CSS = <<<'CSS'
CSS;
//--- Start feature: Removed CSS from this file ---
// $this->headLink()
//     // Require two divs with classes container and main above the og-grid.
//     // ->appendStylesheet($assetUrl('vendor/thumbnail-grid-expanding-preview/css/default.css'))
//     ->appendStylesheet($assetUrl('css/component.css'));

//     //$this->headStyle()->appendStyle($css);

$this->headScript()
//-- Start feature: Corrected javascript file ---
//-- Modified javascript. See: https://github.com/Daniel-KM/ThumbnailGridExpandingPreview/pull/1
//  --- Comment out ---
//  ->appendFile($assetUrl('vendor/thumbnail-grid-expanding-preview/js/grid.js', 'BlockPlus'))
//  ->appendFile($assetUrl('vendor/thumbnail-grid-expanding-preview/js/browse-preview-gallery.js', 'BlockPlus'))
//  --- Respective changes placed in theme js folder ---
    ->appendFile($this->assetUrl('js/grid.js'))
    ->appendFile($this->assetUrl('js/browse-preview-gallery.js'));
//-- End feature: Corrected javascript file ---
?>

<div class="block preview-block">

    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>

    <div class="preview-grid">
        <ul id="og-grid" class="og-grid">
            <?php
            $heading = '';
            $body = '';

            $thumbnailType = $query['thumbnail_type'] ?? $thumbnailType ?? 'square';

            $isMedia = $resourceType === 'media';
            $useItemMetadata = $isMedia && !empty($useItemMetadata);

            $untitled = $translate('[Untitled]');
            $displayInfo = $escapeAttr($translate('Display info'));

            foreach ($resources as $resource):
                $thumbnail = $resource->thumbnail($thumbnailType);
                $media = $resource->primaryMedia();
                if (!$thumbnail && !$media) continue;

                if ($useItemMetadata) {
                    $resource = $resource->item();
                }

                if ($thumbnail) {
                    $mediaThumbnail = $thumbnail->assetUrl();
                    $mediaLarge = $mediaThumbnail;
                } else {
                    $mediaThumbnail = $media->thumbnailUrl($thumbnailType);
                    // Speedup process.
                    $mediaLarge = strtr($mediaThumbnail, ["/$thumbnailType/" => '/large/']);
                }

                if ($showHeading) {
                    $heading = $resource->displayTitle($untitled, $langValue);
                }
                
// ---- Start UM feature: Custom body  -------------- //
                /*  --- Commented out ---
                     if ($showBody) {
                     $body = $resource->displayDescription(null, $langValue);
                     $body .= '<p>'
                         . $translate('More information')
                         . '<br/>'
                         . $resource->linkPretty()
                         . '</p>';}
                */


                if ($showBody):
                    $body = $resource->displayDescription(null, $lang);
                    $body .= '<br/><span class="secondary-button">'
                        . $resource->link("View this collection")
                        . '</span>';
                else:
                    $body = '';
                endif;
// ---- End UM feature: Custom body  -------------- //



            ?>
            
            <li>
               
                <button type="button" aria-label="<?= $displayInfo ?>" data-url="" data-largesrc="<?= $mediaLarge ?>" data-title="<?= $heading ?>" data-description="<?= $escapeAttr($body) ?>">
                    <img loading="lazy" class="button medium-img" src="<?= $mediaThumbnail ?>" alt="<?= $heading ?>"/>
                     <h3><?= $heading ?></h3>
                </button>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php /* // TODO Require some js to fetch data.
        <button id="og-additems" type="button" class="button"><?= $translate('See more') ?></button>
        */ ?>
    </div>

    <?php if ($linkText): ?>
        <?= $hyperlink($linkText, $url('site/resource', ['controller' => $resourceType, 'action' => 'browse'], ['query' => $query], true)) ?>
    <?php endif; ?>

</div>
