<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage Alias of $searchConfig
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 *
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

// This file is based on the original facets.phtml file from module Advanced Search, and is customized to our needs.
// The original file is located here: https://github.com/Daniel-KM/Omeka-S-module-AdvancedSearch/blob/3.4.21/view/search/facets.phtml
// In module versions 3.4.28 and higher, the file is renamed to `facets-list.phtml` and is now located here: https://github.com/Daniel-KM/Omeka-S-module-AdvancedSearch/blob/master/view/search/facets-list.phtml

if (!isset($response) || empty($searchConfig->subSetting('facet', 'facets'))) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchConfig->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchConfig->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displaySubmit = $displayFacetButton ? $searchConfig->subSetting('facet', 'display_submit', 'above') : 'none';
$displayReset = $searchConfig->subSetting('facet', 'display_reset', 'above');
$labelSubmit = $displaySubmit ? $searchConfig->subSetting('facet', 'label_submit', $translate('Apply facets')) : null;
$labelReset = $displayReset ? $searchConfig->subSetting('facet', 'label_reset', $translate('Reset facets')) : null;

$facetActives = $plugins->get('facetActives');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');
$facetSelectRange = $plugins->get('facetSelectRange');
$facetElementsTree = $isFacetModeButton ? $plugins->get('facetCheckboxesTree') : $plugins->get('facetLinksTree');

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchConfig->setting('facet', []);
?>

<aside class="search-facets">

    <?php if ($facetsLabel = $searchConfig->subSetting('facet', 'label', $translate('Facets'))): ?>
        <h3><?= $escape($facetsLabel) ?></h3>
    <?php endif; ?>

    <?php if ($displayActive && count($activeFacets)): ?>
        <h4><?= $translate('Active facets') ?></h4>
        <?= $facetActives(null, $activeFacets, $options) ?>
    <?php endif; ?>

    <form id="form-facets">

        <?php if ($displayFacetButton): ?>
            <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php $r = ($displayReset === 'above' || $displayReset === 'both'); ?>
        <?php $s = ($displayFacetButton && ($displaySubmit === 'above' || $displaySubmit === 'both')); ?>
        <?php if ($r || $s): ?>
            <div class="apply-facets apply-facets-top">
                <?php if ($s): ?>
                    <button id="apply-facets" type="submit"><?= $labelSubmit ?></button>
                <?php endif ?>
                <?php if ($r): ?>
                    <button id="reset-facets" type="reset"><?= $labelReset ?></button>
                <?php endif ?>
            </div>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?>
            <p><?= $translate('No facets.') ?></p>
        <?php else: ?>
            <ul class="search-facets-list">
                <?php foreach ($facets as $name => $facetValues): ?>
                    <?php $facetType = empty($options['facets'][$name]['type']) ? 'Checkbox' : $options['facets'][$name]['type']; ?>
                    <li class="search-facet">
                        <details>
                            <summary>
                                <h4 style="display: inline"><?= $translate($facetLabel($name)) ?></h4>
                            </summary>

                            <!-- Enrich some facets with a search box -->
                            <!-- Many thanks to KU Leuven for sharing the code on which this is based -->
                            <?php if($facetLabel($name) == 'Resource class'):?>
                                <input type="text" id="search-facet-resource-class" oninput="filterFacetOptions('search-facet-resource-class')" placeholder="Type to filter...">
                            <?php endif;?>
                            <?php if($facetLabel($name) == 'Resource template'):?>
                                <input type="text" id="search-facet-resource-template" oninput="filterFacetOptions('search-facet-resource-template')" placeholder="Type to filter...">
                            <?php endif;?>
                            <?php if($facetLabel($name) == 'Collection'):?>
                                <input type="text" id="search-facet-item-set" oninput="filterFacetOptions('search-facet-item-set')" placeholder="Type to filter..." >
                            <?php endif;?>
                            <?php if($facetLabel($name) == 'Author'):?>
                                <input type="text" id="search-facet-author" oninput="filterFacetOptions('search-facet-author')" placeholder="Type to filter..." >
                            <?php endif;?>
                            <?php if($facetLabel($name) == 'Creator'):?>
                                <input type="text" id="search-facet-creator" oninput="filterFacetOptions('search-facet-creator')" placeholder="Type to filter..." >
                            <?php endif;?>

                            <?php if ($facetType === 'Select'): ?>
                                <?= $facetSelect($name, $facetValues, $options) ?>
                            <?php elseif ($facetType === 'SelectRange'): ?>
                                <?= $facetSelectRange($name, $facetValues, $options) ?>
                            <?php elseif ($facetType === 'Tree'): ?>
                                <?= $facetElementsTree($name, $facetValues, $options) ?>
                            <?php else: ?>
                                <?= $facetElements($name, $facetValues, $options) ?>
                            <?php endif; ?>
                        </details>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php $r = ($displayReset === 'below' || $displayReset === 'both'); ?>
        <?php $s = ($displayFacetButton && ($displaySubmit === 'below' || $displaySubmit === 'both')); ?>
        <?php if ($r || $s): ?>
            <div class="apply-facets apply-facets-bottom">
                <?php if ($s): ?>
                    <button id="apply-facets" type="submit"><?= $labelSubmit ?></button>
                <?php endif ?>
                <?php if ($r): ?>
                    <button id="reset-facets" type="reset"><?= $labelReset ?></button>
                <?php endif ?>
            </div>
        <?php endif; ?>

    </form>

</aside>

<script>
    // Javascript function that implements the search box in the facets
    function filterFacetOptions(elementId) {
        // Declare variables
        var input, filter, ul, li, label, i, txtValue;
        input = document.getElementById(elementId);
        filter = input.value.toUpperCase();
        details = input.parentElement;
        ul = details.getElementsByTagName('ul')[0];
        li = ul.getElementsByTagName('li');

        // Loop through all list items, and hide those who don't match the search query
        for (i = 0; i < li.length; i++) {
            label = li[i].getElementsByTagName("label")[0];
            txtValue = label.textContent || label.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }
        }
    }
</script>