<?php
// Customized version of 'facets-list.phtml' from module 'Advanced Search'.
// Customizations:
// - custom feature 'Search within facet values': Adds a search box to some facets in order to filter facet values.
//     This feature can be activated in the 'Advanced Search' section of the theme settings.
//     Many thanks to KU Leuven for sharing the code on which this was based initially.

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation|null $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * @var \Omeka\Api\Representation\ItemSetRepresentation|null $itemSet
 */

if (!isset($response)) return;

$searchFacets = $searchConfig->subSetting('facet', 'facets', []);
if (!count($searchFacets)) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$isFacetModeButton = !in_array($searchConfig->subSetting('facet', 'mode'), ['link', 'js']);
$displayActive = (bool) $searchConfig->subSetting('facet', 'display_active', true);
$displayRefine = (bool) $searchConfig->subSetting('facet', 'display_refine', true);
$labelRefine = $displayRefine ? $searchConfig->subSetting('facet', 'label_refine', 'Refine search') : null;
$displayFacetButton = $isFacetModeButton && ($displayActive || !empty($facets));
$displaySubmit = $displayFacetButton ? $searchConfig->subSetting('facet', 'display_submit', 'above') : 'none';
$labelSubmit = $displaySubmit ? $searchConfig->subSetting('facet', 'label_submit', 'Apply facets') : null;
$displayReset = $searchConfig->subSetting('facet', 'display_reset', 'above');
$labelReset = $displayReset ? $searchConfig->subSetting('facet', 'label_reset', 'Reset facets') : null;

$facetActives = $plugins->get('facetActives');
$facetElements = $plugins->get('facetElements');

// BEGIN custom feature 'Search within facet values'
$facetSearchList=str_replace(', ',',',$this->themeSetting('FacetSearchFilter'));
$facetTagList=explode(",", $facetSearchList);
$facetTypes= json_encode($facets);
// END custom feature 'Search within facet values'

// TODO Remove item sets facets early when item set redirects to search.
// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}
?>

<div id="search-facets" class="facets">

    <?php if ($label = $searchConfig->subSetting('facet', 'label', 'Facets')): ?>
        <h3><?= $escape($translate($label)) ?></h3>
    <?php endif; ?>

    <?php if ($displayActive && count($activeFacets)): ?>
        <?php if ($label = $searchConfig->subSetting('facet', 'label_active_facets', 'Active facets')): ?>
            <h4><?= $escape($translate($label)) ?></h4>
        <?php endif; ?>
        <?= $facetActives(null, $activeFacets, $searchConfig->setting('facet')) ?>
    <?php endif; ?>

    <form id="facets-form">

        <?php if ($displayFacetButton): ?>
            <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'refine', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php $displayButtonReset = $displayReset === 'above' || $displayReset === 'both'; ?>
        <?php $displayButtonSubmit = $displayFacetButton && ($displaySubmit === 'above' || $displaySubmit === 'both'); ?>
        <?php if ($displayButtonReset || $displayButtonSubmit): ?>
            <div class="facets-actions facets-actions-top">
                <?php if ($displayButtonSubmit): ?>
                    <button id="facets-apply" class="button facets-apply" type="submit"><?= $escape($translate($labelSubmit)) ?></button>
                <?php endif; ?>
                <?php if ($displayButtonReset): ?>
                    <button id="facets-reset" class="button facets-reset" type="reset"><?= $escape($translate($labelReset)) ?></button>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php if ($displayRefine): ?>
            <div class="facets-refine">
                <?php if ($labelRefine): ?>
                    <h4><label for="search-refine"><?= $escape($translate($labelRefine)) ?></label></h4>
                <?php endif; ?>
                <input id="search-refine" name="refine" class="search-refine" value="<?= $escape($query->getQueryRefine()) ?>"<?= $labelRefine ? ' data-placeholder="' . $escapeAttr($translate($labelRefine)) . '"' : '' ?>/>
                <?php if (!$displayButtonSubmit): ?>
                    <button id="search-refine-submit" class="button search-refine" type="submit"><?= $escape($translate('Submit')) ?></button>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?>
            <?php if ($label = $searchConfig->subSetting('facet', 'label_no_facets', 'No facets')): ?>
                <p><?= $escape($translate($label)) ?></p>
            <?php endif; ?>
        <?php else: ?>
            <ul class="facets-list">
                <?php foreach ($facets as $name => $facetValues): ?>
                    <?php $facetParams = $searchFacets[$name]; ?>
                    <?php $hasState = in_array($facetParams['state'] ?? '', ['expand', 'collapse', 'collapse_unless_set']); ?>
                    <li class="facet<?= empty($facetParams['attributes']['class']) ? '' : ' ' . $escapeAttr($facetParams['attributes']['class']) ?>">
                        <?php if ($hasState): ?>
                            <?php $stateExpand = $facetParams['state'] === 'expand' || ($facetParams['state'] === 'collapse_unless_set' && !empty($activeFacets[$name])); ?>
                            <button type="button" class="button facet-button <?= $stateExpand ? 'collapse' : 'expand' ?>" aria-label="<?= $translate($stateExpand ? 'Collapse' : 'Expand') ?>" data-label-expand="<?= $translate('Expand') ?>" data-label-collapse="<?= $translate('Collapse') ?>"><?= $escape($translate($facetParams['label'] ?? $name)) ?></button>
                        <?php else: ?>
                            <h4><?= $escape($translate($facetParams['label'] ?? $name)) ?></h4>
                        <?php endif; ?>
                        <div class="facet-elements<?= $hasState ? ' collapsible' : '' ?>"<?= $hasState && $facetParams['state'] === 'collapse' ? ' hidden="hidden"' : '' ?>>

                            <!-- BEGIN custom feature 'Search within facet values'-->
                            <?php $facetFieldName= 'facet-search-filter-'.$name; ?>
                            <?php if(in_array($facetParams['label'],$facetTagList)):?>
                                <input type="text" id="<?php echo $facetFieldName?>" oninput="filterFacetOptions('<?php echo $facetFieldName?>')" placeholder="Type to filter...">
                            <?php endif;?>
                            <!-- END custom feature 'Search within facet values'-->

                            <?= $facetElements($name, $facetValues, $facetParams) ?>
                            <?php if (($facetParams['more'] ?? '') !== '' && in_array($facetParams['type'] ?? '', ['', 'Checkbox', 'Link', 'Tree', 'TreeLink', 'Thesaurus', 'ThesaurusLink']) && count($facetValues) > (int) $facetParams['more']): ?>
                                <div class="facet-see-more">
                                    <button type="button" class="button facet-see-more-or-less expand" data-default-count="<?= (int) $facetParams['more'] ?>" data-more-count="<?= count($facetValues) - (int) $facetParams['more'] ?>" data-label-see-more="<?= $escapeAttr($translate('See more')) ?>" data-label-see-less="<?= $escapeAttr($translate('See less')) ?>"><?= $escape($translate('See more')) ?></button>
                                </div>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php $displayButtonReset = $displayReset === 'below' || $displayReset === 'both'; ?>
        <?php $displayButtonSubmit = $displayFacetButton && ($displaySubmit === 'below' || $displaySubmit === 'both'); ?>
        <?php if ($displayButtonReset || $displayButtonSubmit): ?>
            <div class="facets-actions facets-actions-bottom">
                <?php if ($displayButtonSubmit): ?>
                    <button id="facets-apply" class="button facets-apply" type="submit"><?= $escape($translate($labelSubmit)) ?></button>
                <?php endif; ?>
                <?php if ($displayButtonReset): ?>
                    <button id="facets-reset" class="button facets-reset" type="reset"><?= $escape($translate($labelReset)) ?></button>
                <?php endif; ?>
            </div>
        <?php endif; ?>

    </form>

</div>

<!-- BEGIN custom feature 'Search within facet values' -->
<script>
    // Javascript function that implements the search box in the facets
    function filterFacetOptions(elementId) {
        // Declare variables
        var input, filter, ul, li, label, i, txtValue;
        input = document.getElementById(elementId);
        filter = input.value.toUpperCase();
        details = input.parentElement;
        ul = details.getElementsByTagName('ul')[0];
        li = ul.getElementsByTagName('li');

        // Loop through all list items, and hide those who don't match the search query
        for (i = 0; i < li.length; i++) {
            label = li[i].getElementsByTagName("label")[0];
            txtValue = label.textContent || label.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }
        }
    }
</script>
<!-- END custom feature 'Search within facet values' -->