<?php
// Customized version of 'view/search/search-form-simple.phtml' from module 'AdvancedSearch' version 3.3.6.19
// Customizations:
// - custom feature Use searchController from theme settings
// - custom feature Render HTML form directly instead of using partial

$translate = $this->plugin('translate');

// BEGIN custom feature Use searchController from theme settings
// $searchAction uses the "->url() API representation method". Info here: https://omeka.org/s/docs/developer/api/representations/#urls
// The value for 'controller' in $searchAction needs to match the path of the search page that is configured in "Search Manager".
// If you're using a custom controller (i.e. 'solr-obs' or 'my-search') you can configure this in the theme settings (Admin -> Site -> Theme -> Edit theme settings).
// If nothing is configured in the theme settings, the default value 'find' is used.

if ($this->themeSetting('searchController')) {
    $searchAction=$this->url('site/resource', ['controller' => '' . $this->themeSetting('searchController') . '' ,'action' => null], true);
} else {
    $searchAction = $this->url('site/resource', ['controller' => 'find', 'action' => null], true);
}
// END custom feature Use searchController from theme settings

$searchValue = $this->escapeHtml($this->params()->fromQuery('q', ''));
?>

<!-- BEGIN custom feature Render HTML form directly instead of using partial -->
<form action="<?php echo $this->escapeHtml($searchAction); ?>" id="search-form">
    <input type="text" name="q" value="<?php echo $searchValue; ?>"
        placeholder="<?php echo $translate('Search'); ?>"
        aria-label="<?php echo $translate('Search'); ?>">
    <button type="submit"><?php echo $translate('Search'); ?></button>
</form>
<!-- END custom feature Render HTML form directly instead of using partial -->
