<?php
$timestamp=time();
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css')); //Generic (institutional?) Style elements
$this->headLink()->prependStylesheet($this->assetUrl('css/search.css')); //Modified Advanced Search style elements of theme (PV-2023-02-06)
//$this->headLink()->prependStylesheet($this->assetUrl('css/sitestyle.css')); //Specific Style Elements.
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Nunito:wght@300&display=swap');
$this->headScript()->prependFile($this->assetUrl('js/desandroimagesloaded.js'));
$this->headScript()->prependFile($this->assetUrl('js/desandromasonry.js'));
$this->headScript()->prependFile($this->assetUrl('js/um_theme.js'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));


$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$summary = $this->pageTitle($site->summary());
//$logo = $this->themeSettingAssetUrl('logo');
$leftLogo = $this->assetUrl('img/left-logo-sample.png');
$rightLogo = $this->assetUrl('img/right-logo-sample.png');
$footerLogo = $this->assetUrl('img/footer-logo-sample.png');
$facebookLogo=$this->assetUrl('img/facebook.png');
$instagramLogo=$this->assetUrl('img/Instagram.png');
$twitterLogo=$this->assetUrl('img/Twitter.png');
$linkedinLogo=$this->assetUrl('img/LinkedIn.png');
$youtubeLogo=$this->assetUrl('img/Youtube.png');

//if ($logo):
//    $title = '<img src="' . $this->escapeHtml($logo) . '">';
//endif;
$userBar = $this->partial('common/user-bar', ['site' => $site]);
$query = $this->params()->fromQuery();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head><meta charset="gb18030">
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php //echo $userBar; ?>
        <header <?php 
        if (strlen($userBar) > 1){ echo "class='logged-in'"; } ?>>
            <div id="top-bar">
                <?php if ($this->themeSetting('logoLeft') && $this->themeSetting('logoRight')): ?>
                    <a id="institution-logo" href="<?php echo $site->url(); ?>"><img src="<?php echo $this->themeSettingAssetUrl('logoLeft'); ?>" title="Logo" /></a>
					<div id="site-header-title"><?php echo $summary; ?></div>
                    <!--<a href="<?php //echo $site->url(); ?>" class="site-title"><img src="<?php //echo $this->themeSettingAssetUrl('logoRight'); ?>" title="Logo"></a>-->
                <?php elseif ($this->themeSetting('logoLeft')): ?>
                    <a id="institution-logo" href="http://nonviolence.rutgers.edu/"><img src="<?php echo $this->themeSettingAssetUrl('logoLeft'); ?>" title="Logo" /></a>
                <?php elseif ($this->themeSetting('logoRight')): ?>
                    <a href="<?php echo $site->url(); ?>" class="institution-logo"><?php echo $this->pageTitle($site->title()); ?></a>
                    <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logoRight'); ?>" title="Logo"></a>
					
                <?php else: ?>
                    <a href="<?php echo $site->url(); ?>" class="institution-logo"><img src="<?php echo $leftLogo; ?>" title="Site logo"/></a>
                    <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $rightLogo; ?>" title="Institutional logo"></a>
					
                <?php endif; ?>
            </div>
            
            <div id="header-main">
			<div id="MsgDiv">test</div>
                <nav>
                    <?php echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1]);?>
				
                </nav>
				
				<div id="search-head">
			  <?php 
				$whatPage = $_SERVER['REQUEST_URI'];
				//echo $whatPage;
				$displaySearch = 1;
				if($whatPage=="/" || $whatPage=="/home" || $whatPage=="/index" || $whatPage=="/about" || $whatPage=="/item/search" || $whatPage=="/explore") $displaySearch=0;
				?>
				<?php if($_SERVER['REQUEST_URI'] != $site->url()  && $displaySearch==1){ ?>
					<div id="search" <?php 
				if (strlen($userBar) > 1){ echo "class='logged-in'"; } ?>>
						<!--div id="interior-hero-content"-->
						
						<?php echo $this->partial('search/search-form-simple'); ?>
							<?php //echo $this->partial('common/search-form'); ?>
							<?php //echo $this->hyperlink(); ?>
						<!--/div-->
					</div>
				<?php } ?>
						
				</div>
				
				<div id="nav-about">
				<?php if ($this->themeSetting('supportPage')):?>
			
                    <a href="<?php echo $this->themeSetting('supportPage') ?>" target="_blank">Support</a>
					<?php else: ?>
					<a href="https://library.maastrichtuniversity.nl" target="_blank">Support</a>
				<?php endif; ?>
				</div>
            </div>
		
			
        </header>
      
        <div id="content" role="main">
            <?php if($_SERVER['REQUEST_URI'] != $site->url()){ ?>
                    <?php echo $this->content; ?>
            <?php } else { ?>         
                <?php echo $this->content; ?>
            <?php } ?>
        </div>
        <?php //if($_SERVER['REQUEST_URI'] != $site->url()){ ?>
            <footer>
			<div class="footer-wrapper">
			
				 <?php if ($this->themeSetting('logoFooter')): ?>
					<div id="footer-logo"><img src="<?php echo $this->themeSettingAssetUrl('logoFooter'); ?>" title="footer logo"></div>
				 <?php endif; ?>
				 <div class="footer-items">
					<?php if ($footerContent = $this->themeSetting('footer')): ?>
					<?php echo $footerContent; ?>
					<?php else: ?>
						<?php echo $this->translate('Powered by Omeka S'); ?>
					<?php endif; ?>
					<div class="footer-col">
					<h3>Follow us on</h3>
						<div class="social">
						<a href="https://facebook.com/MaastrichtUniversityLibrary" target="_blank" rel="noopener">
							<img decoding="async" loading="lazy" src="<?php echo $facebookLogo; ?>"/></a>
						
						<a href="https://www.instagram.com/maastrichtuniversitylibrary/" target="_blank" rel="noopener">
							<img decoding="async" loading="lazy" src="<?php echo $instagramLogo; ?>"/></a>
						<a href="https://www.linkedin.com/company/maastricht-university-library/?viewAsMember=true" target="_blank" rel="noopener">
								<img decoding="async" loading="lazy" src="<?php echo $linkedinLogo; ?>"/></a>
						<a href="https://twitter.com/um_library" target="_blank" rel="noopener">
								<img decoding="async" loading="lazy" src="<?php echo $twitterLogo; ?>"/></a>
						<a href="https://www.youtube.com/channel/UC4Wa2-Bx-TE3U3weAIAnfKw" target="_blank" rel="noopener">
								<img decoding="async" loading="lazy" src="<?php echo $youtubeLogo; ?>"/></a>
						
						</div>
						</div>	
					
				</div>
			</div>
            </footer>
        <?php //} ?> 
    </body>
</html>
